const chatFaceData=[
    {
        id:1,
        name:'Aida',
        image:'https://github.com/shyanukant/aurora/blob/main/App/Assets/chat.png',
        primary:'#FFC107',
        secondary:''
    },
    {
        id:2,
        name:'Chom',
        image:'https://github.com/shyanukant/aurora/blob/main/App/Assets/aibuddy2.png',
        primary:'#E53057',
        secondary:''
    },
    {
        id:3,
        name:'Luna',
        image:'https://github.com/shyanukant/aurora/blob/main/App/Assets/aibuddy.png',
        primary:'#3B96D2',
        secondary:''
    },
    {
        id:4,
        name:'Nix',
        image:'https://github.com/shyanukant/aurora/blob/main/App/Assets/aibuddy3.png',
        primary:'#37474F',
        secondary:''
    },
    {
        id:5,
        name:'Zee',
        image:'https://github.com/shyanukant/aurora/blob/main/App/Assets/aibuddy4.png',
        primary:'#2473FE',
        secondary:''
    },
];

export default chatFaceData;